nelmio_api_doc:
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Bilemo API
            description: API description for Bilemo App
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value should be : {Bearer TOKEN} obtain by /api/login_check'
                name: Authorization
                in: header
                default: 'Bearer '
        paths:
            /api/login_check:
                post:
                    tags:
                        - Security
                    sumarry: Authentication
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/AuthenticationContent"

        definitions:
            AuthenticationContent:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            CreateClientInput:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
                    role:
                        type: string
                        required: false
            ListPhoneOutput:
                type: array
                items:
                    $ref: "#/definitions/PhoneOutput"
            PhoneOutput:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                        description: Unique identifier of phone
                    name:
                        type: string
                        required: true
                        description: Phone's name
                    os:
                        type: string
                        required: true
                        description: Phone's OS
                    memory:
                        type: string
                        required: true
                        description: Phone's memory storage
                    links:
                        type: array
                        items:
                            $ref: "#/definitions/LinkOutput"
            LinkOutput:
                type: object
                properties:
                    method:
                        type: string
                        required: true
                        description: Verb HTTP to call url related
                    type:
                        type: string
                        required: true
                        description: Type of link. self, delete, post, list
                    url:
                        type: string
                        required: true
                        description: Url to access related link
            JwtErrorOutput:
                type: object
                properties:
                    status:
                        type: integer
                        required: true
                        description: Status code error
                    message:
                        type: string
                        required: true
                        description: Error message occured
