nelmio_api_doc:
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Bilemo API
            description: API description for Bilemo App
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value should be : {Bearer TOKEN} obtain by /api/login_check'
                name: Authorization
                in: header
                default: 'Bearer '
        paths:
            /api/login_check:
                post:
                    tags:
                        - Security
                    sumarry: Authentication
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/AuthenticationContent"
        definitions:
            AuthenticationContent:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            JwtErrorOutput:
                type: object
                properties:
                    status:
                        type: integer
                        required: true
                    message:
                        type: string
                        required: true
            ListPhoneOutput:
                type: array
                items:
                    $ref: "#/definitions/PhoneItemListOutput"
            PhoneItemListOutput:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
                    os:
                        type: string
                        required: true
                    brand:
                        type: string
                        required: true
                    memory:
                        type: string
                        required: true
                    _links:
                        type: array
                        items:
                            $ref: "#/definitions/LinkItemOutput"
            LinkItemOutput:
                type: object
                properties:
                    type:
                        type: string
                        required: true
                    method:
                        type: string
                        required: true
                    url:
                        type: string
                        required: true
