nelmio_api_doc:
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Bilemo API
            description: API description for Bilemo App
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value should be : {Bearer TOKEN} obtain by /api/login_check'
                name: Authorization
                in: header
                default: 'Bearer '
        paths:
            /api/login_check:
                post:
                    tags:
                        - Security
                    sumarry: Authentication
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/AuthenticationContent"


