parameters:
    locale: 'en'
    prodfixtures: '%kernel.project_dir%/config/fixtures/prod/00_load.yml'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $prodFixtures: '%prodfixtures%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Domain/Model,Domain/DoctrineMigrations,Tests,Kernel.php,CacheKernel.php}'

    App\UI\Actions\:
        resource: '../src/UI/Actions'
        tags: ['controller.service_arguments']

    App\Application\Subscribers\Core\TimestampableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Application\Listeners\JWT\JWTAuthFailure:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    App\Application\Listeners\JWT\JWTNotFound:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
